### PR TITLE
SRCH-4041 use Ruby 3.0.6

### PR DESCRIPTION
**Pull request by MothOnMars**
## Summary
This PR updates I14y to use Ruby 3.0.6 and removes 2.7 from the test matrix.
 
### Checklist
Please ensure you have addressed all concerns below before marking a PR "ready for review" or before requesting a re-review. If you cannot complete an item below, replace the checkbox with the ⚠️ `:warning:` emoji and explain why the step was not completed.
 
#### Functionality Checks
 
- [x] You have merged the latest changes from the target branch (usually `main`) into your branch.
  
- [x] Your primary commit message is of the format **SRCH-#### \<description\>** matching the associated Jira ticket.

- [x] PR title is either of the format **SRCH-#### \<description\>** matching the associated Jira ticket (i.e. "SRCH-123 implement feature X"), or **Release - SRCH-####, SRCH-####, SRCH-####** matching the Jira ticket numbers in the release.
 
⚠️  Automated checks pass. If Code Climate checks do not pass, explain reason for failures:
Tests are passing, but the Github/CircleCi integration still thinks that results from the removed versions are forthcoming. I expect this issue will resolve once this PR is merged. Raw CircleCi results: 
https://app.circleci.com/pipelines/github/MothOnMars/i14y?branch=ruby_305_4041
 
#### Process Checks

- [x] You have specified at least one "Reviewer".

### CODE REVIEW

**Review by lorawoodford — APPROVED** [review]
LGTM

**Review by lorawoodford — DISMISSED** [review]
LGTM

**Comment by MothOnMars** [comment]
Adding the "do not merge" label. This won't be deployable until Ruby 3.0.6 is installed in production: https://cm-jira.usa.gov/browse/SRCH-3862

**Comment by MothOnMars** [comment]
@lorawoodford , this requires a re-review. Our PRs currently require status checks from specific Ruby versions, so I've added those versions back to the test matrix. The old versions will be removed, and the PR status checks will be updated in a follow-up ticket: https://cm-jira.usa.gov/browse/SRCH-3880

**Review by lorawoodford — APPROVED** [review]
LGTM (will need to be brought up to date with main, but I know this is gonna be hanging out for a bit so this likely won't be the last time that bump is needed).

**Pull request merged**
