### PR TITLE
compute and store filename extension for documents

### PR DESCRIPTION
**Pull request by noremmie**

### CODE REVIEW

**Comment by noremmie** [comment]
@MothOnMars isn't it safe for me to remove the explicit Ruby version specification from `Gemfile` as long as we keep it specified in `.circleci/config.yml`?

**Comment by MothOnMars** [comment]
`.circleci/config.yml` only tells CircleCI what version to use, but it won't tell Bundler, rvm, etc. what version to use.

**Comment by noremmie** [comment]
@MothOnMars I wanted to remove that exact Ruby version specification from `Gemfile` because it can prevent us from being able to deploy i14y whenever a new version of Ruby becomes available. That's why I was saying it's more trouble than it's worth. But what I'm hearing from you is that it actually is worth the trouble, so I'll leave it in there. I'll bump it and the Ruby versions specified elsewhere.

**Comment by MothOnMars** [comment]
👍 thanks

**Comment by noremmie** [comment]
I got some more feedback from @MothOnMars that I'm going to address before re-opening this PR.

**Pull request closed without merging**
