### PR TITLE
SRCH-1031 run Elasticsearch 6.8 using Docker

### PR DESCRIPTION
**Pull request by MothOnMars**
- add Basic Usage instructions to README

### CODE REVIEW

**Comment by MothOnMars** [comment]
closing temporarily to make some tweaks...

**Comment by ondrae** [comment]
Without your tweaks, it looks good though. Everything works in the instructions. Let me know when to recheck it.

**Comment by MothOnMars** [comment]
Thanks, @ondrae . I remembered that using the standard 9200 port will simplify things when I start testing multiple versions of ES, so I switched everything back to the standard port 9200 (5601 for Kibana).

**Comment by ondrae** [comment]
Review now.

**Pull request merged**
