### PR TITLE
[#153602483] Disable read-only mode after testing read-only mode

### PR DESCRIPTION
**Pull request by noremmie**

### CODE REVIEW

**Comment by noremmie** [comment]
@MothOnMars my last commit in master introduced intermittent spec failures because I was sloppy about not turning read-only mode off after read-only-mode-related tests. This fixes it by always turning read-only mode off after each example.

**Comment by MothOnMars** [comment]
I'm thinking it might make sense to move all the before/after setup regarding the read-only mode into the shared examples. That would consolidate the duplicate before/after/let statements in `documents_spec` & `collections_spec` into one file, and ensure that those statements aren't cluttering up spec files where they are not used (and may also be prone to fragility like this).

**Comment by noremmie** [comment]
@MothOnMars I can't move the read-only mode `before`/`after` blocks into the shared examples because the request that's being tested is itself made inside a `before` block. Any other `before` blocks I add to the shared examples won't get run until after the request is made, and that's too late to set or unset read-only mode.

My approach to adding the new specs for b8916c7eccb271f42c36902b28304e64f0169911 was to find all the success cases and for each case additionally turn on read-only mode so that an otherwise-successful request gets denied due to read-only mode being set. I don't think I can move the `before`/`after` blocks into the shared examples without copying all the "success case" code into those shared examples too.

How would you feel about me trying to put all the `before`/`after` blocks into a new appropriately-named shared context instead? That's the only way I can think of to move those blocks out of  `collections_spec.rb` and `documents_spec.rb` without major edits at this point.

**Comment by MothOnMars** [comment]
Ah, I see the dilemma. Let's let sleeping dogs lie and stick with your original approach (for now), in which case 👍

**Pull request merged**
